<?php
/**
 * Plugin Name: Batch Sync Test - Random Users
 * Plugin URI: https://arraypress.com
 * Description: Test plugin for Batch Sync Manager - generates 100 random users
 * Version: 1.0.2
 * Author: ArrayPress
 * Author URI: https://arraypress.com
 * License: GPL2+
 */

declare( strict_types=1 );

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

require_once __DIR__ . '/vendor/autoload.php';

/**
 * Main plugin class
 */
class Batch_Sync_Test_Plugin {

	/**
	 * Batch sync manager instance
	 *
	 * @var \ArrayPress\BatchSync\Manager
	 */
	public $batch_sync;

	/**
	 * Single instance
	 *
	 * @var self
	 */
	private static $instance = null;

	/**
	 * Get instance
	 *
	 * @return self
	 */
	public static function instance() {
		if ( is_null( self::$instance ) ) {
			self::$instance = new self();
		}

		return self::$instance;
	}

	/**
	 * Constructor
	 */
	private function __construct() {
		$this->init_batch_sync();
		$this->hooks();
	}

	/**
	 * Initialize batch sync manager
	 *
	 * @return void
	 */
	private function init_batch_sync(): void {
		$this->batch_sync = new \ArrayPress\BatchSync\Manager( 'batch_sync_test' );

		// Register sync handlers
		$this->batch_sync->register( 'random_users', [
			'callback'    => [ $this, 'sync_random_users' ],
			'title'       => __( 'Generate Random Users', 'batch-sync-test' ),
			'description' => __( 'This will generate 100 random test users in your WordPress site.', 'batch-sync-test' ),
			'button_text' => __( 'Start Generation', 'batch-sync-test' ),
			'singular'    => 'user',
			'plural'      => 'users',
			'limit'       => 10, // Process 10 users per batch
			'capability'  => 'create_users',
			'icon'        => 'admin-users',
			'auto_close'  => true, // Auto-close and refresh on success
		] );
	}

	/**
	 * Setup hooks
	 *
	 * @return void
	 */
	private function hooks(): void {
		add_action( 'restrict_manage_users', [ $this, 'add_sync_button' ] );
	}

	/**
	 * Add sync button to users page
	 *
	 * @return void
	 */
	public function add_sync_button(): void {
		$this->batch_sync->button( 'random_users' );
	}

	/**
	 * Sync random users callback
	 *
	 * @param string $starting_after Pagination cursor
	 * @param int    $limit          Batch size
	 * @param array  $options        Options
	 *
	 * @return array Batch result
	 */
	public function sync_random_users( string $starting_after, int $limit, array $options ): array {
		$total_users = 100;
		$start_index = $starting_after ? (int) $starting_after : 0;
		$end_index   = min( $start_index + $limit, $total_users );

		$results = [
			'items'           => [],
			'has_more'        => $end_index < $total_users,
			'last_id'         => (string) $end_index,
			'estimated_total' => $total_users, // Tell frontend the total
		];

		// Generate users for this batch
		for ( $i = $start_index; $i < $end_index; $i ++ ) {
			// Small delay to simulate processing
			usleep( 50000 ); // 50ms

			$user_data = $this->generate_user_data( $i + 1 );

			$item = [
				'id'    => $i + 1,
				'name'  => $user_data['display_name'],
				'error' => null
			];

			try {
				$user_id = wp_insert_user( $user_data );

				if ( is_wp_error( $user_id ) ) {
					$item['error'] = $user_id->get_error_message();
				}
			} catch ( Exception $e ) {
				$item['error'] = $e->getMessage();
			}

			$results['items'][] = $item;
		}

		return $results;
	}

	/**
	 * Generate random user data
	 *
	 * @param int $index User index
	 *
	 * @return array User data
	 */
	private function generate_user_data( int $index ): array {
		$first_names = [
			'James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer', 'Michael', 'Linda',
			'William', 'Barbara', 'David', 'Elizabeth', 'Richard', 'Susan', 'Joseph', 'Jessica',
		];

		$last_names = [
			'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis',
			'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas',
		];

		$first_name = $first_names[ array_rand( $first_names ) ];
		$last_name  = $last_names[ array_rand( $last_names ) ];
		$username   = strtolower( $first_name . '.' . $last_name . '.' . $index );
		$email      = strtolower( $first_name . '.' . $last_name . '.' . $index . '@example.com' );

		return [
			'user_login'   => $username,
			'user_email'   => $email,
			'user_pass'    => wp_generate_password(),
			'first_name'   => $first_name,
			'last_name'    => $last_name,
			'display_name' => $first_name . ' ' . $last_name,
			'role'         => 'subscriber',
			'description'  => 'Test user generated by Batch Sync Test plugin',
		];
	}

}

/**
 * Get plugin instance
 *
 * @return Batch_Sync_Test_Plugin
 */
function batch_sync_test() {
	return Batch_Sync_Test_Plugin::instance();
}

// Initialize
batch_sync_test();